// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $admin_verified from "./routes/admin/verified.tsx";
import * as $api_cache_stats from "./routes/api/cache/stats.ts";
import * as $api_coins_search from "./routes/api/coins/search.ts";
import * as $api_price_chart from "./routes/api/price/chart.ts";
import * as $api_price_coingecko from "./routes/api/price/coingecko.ts";
import * as $api_price_nft from "./routes/api/price/nft.ts";
import * as $api_price_token from "./routes/api/price/token.ts";
import * as $api_search from "./routes/api/search.ts";
import * as $api_signals_username_ from "./routes/api/signals/[username].ts";
import * as $api_verified_index from "./routes/api/verified/index.ts";
import * as $index from "./routes/index.tsx";
import * as $profile_username_ from "./routes/profile/[username].tsx";
import * as $AdminVerified from "./islands/AdminVerified.tsx";
import * as $PriceChart from "./islands/PriceChart.tsx";
import * as $RelativeTime from "./islands/RelativeTime.tsx";
import * as $SearchForm from "./islands/SearchForm.tsx";
import * as $SignalPerformance from "./islands/SignalPerformance.tsx";
import * as $SignalsForm from "./islands/SignalsForm.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
    "./routes/admin/verified.tsx": $admin_verified,
    "./routes/api/cache/stats.ts": $api_cache_stats,
    "./routes/api/coins/search.ts": $api_coins_search,
    "./routes/api/price/chart.ts": $api_price_chart,
    "./routes/api/price/coingecko.ts": $api_price_coingecko,
    "./routes/api/price/nft.ts": $api_price_nft,
    "./routes/api/price/token.ts": $api_price_token,
    "./routes/api/search.ts": $api_search,
    "./routes/api/signals/[username].ts": $api_signals_username_,
    "./routes/api/verified/index.ts": $api_verified_index,
    "./routes/index.tsx": $index,
    "./routes/profile/[username].tsx": $profile_username_,
  },
  islands: {
    "./islands/AdminVerified.tsx": $AdminVerified,
    "./islands/PriceChart.tsx": $PriceChart,
    "./islands/RelativeTime.tsx": $RelativeTime,
    "./islands/SearchForm.tsx": $SearchForm,
    "./islands/SignalPerformance.tsx": $SignalPerformance,
    "./islands/SignalsForm.tsx": $SignalsForm,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
